//! Package emission helpers.

use std::path::Path;

use ed25519_dalek::SigningKey;
use plc_ir::IrModule;
use plc_package::{signing_key_from_seed, Manifest, PackageBuilder};

use crate::error::{CompileError, ErrorCode};

/// Build `.spkg` bytes from module + manifest.
pub fn build_spkg(
    module: &IrModule,
    manifest: Manifest,
    signing_seed_hex: Option<&str>,
) -> Result<Vec<u8>, CompileError> {
    let builder = PackageBuilder::new(manifest).section_module(module)?;
    let builder = if let Some(seed) = signing_seed_hex {
        let seed_bytes = plc_package::hex_decode_n::<32>(seed).map_err(|e| {
            CompileError::new(ErrorCode::EPackage, format!("bad signing seed: {e}"))
        })?;
        let key = signing_key_from_seed(&seed_bytes);
        builder.sign(&key)
    } else {
        builder.unsigned()
    };
    Ok(builder.to_bytes()?)
}

/// Optional spasm dump for debugging (best-effort disassembly-like listing).
pub fn emit_spasm_listing(module: &IrModule) -> String {
    use plc_ir::{decode_instruction, Opcode};
    let mut out = String::new();
    out.push_str(&format!(
        "; generated by plc-compiler\n.header data_size={} retain_size={} input_slots={} output_slots={}\n",
        module.data_size, module.retain_size, module.input_slots, module.output_slots
    ));
    for e in &module.entries {
        if e.is_user_fb {
            out.push_str(&format!(".entry {} fb\n", e.name));
        } else {
            out.push_str(&format!(".entry {}\n", e.name));
        }
        let mut pc = e.pc as usize;
        let end = module
            .entries
            .iter()
            .map(|x| x.pc as usize)
            .filter(|p| *p > e.pc as usize)
            .min()
            .unwrap_or(module.code.len());
        while pc < end && pc < module.code.len() {
            match decode_instruction(&module.code, pc) {
                Ok((instr, size)) => {
                    out.push_str(&format!("  {instr:?}\n"));
                    pc += size;
                    if matches!(
                        instr,
                        plc_ir::DecodedInstr::Simple {
                            op: Opcode::Halt | Opcode::Ret,
                            ..
                        }
                    ) {
                        break;
                    }
                }
                Err(_) => break,
            }
        }
    }
    out
}

/// Write bytes to a path.
pub fn write_file(path: &Path, bytes: &[u8]) -> Result<(), CompileError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| CompileError::new(ErrorCode::EPackage, format!("mkdir: {e}")))?;
    }
    std::fs::write(path, bytes)
        .map_err(|e| CompileError::new(ErrorCode::EPackage, format!("write: {e}")))
}

/// Load Ed25519 seed hex file (64 hex chars).
pub fn load_seed_file(path: &Path) -> Result<String, CompileError> {
    let s = std::fs::read_to_string(path)
        .map_err(|e| CompileError::new(ErrorCode::EPackage, format!("read seed: {e}")))?;
    Ok(s.trim().to_string())
}

/// Silence unused import when signing path unused in some builds.
#[allow(dead_code)]
fn _signing_key_type(_: &SigningKey) {}
